name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');

            // Read CHANGELOG.md for release notes
            let releaseNotes = 'See [CHANGELOG.md](CHANGELOG.md) for details.';
            try {
              const changelog = fs.readFileSync('CHANGELOG.md', 'utf8');
              const version = '${{ steps.get_version.outputs.VERSION }}';
              const versionRegex = new RegExp(`## \\[${version.replace('v', '')}\\]([\\s\\S]*?)(?=## \\[|$)`);
              const match = changelog.match(versionRegex);
              if (match && match[1]) {
                releaseNotes = match[1].trim();
              }
            } catch (error) {
              console.log('Could not read CHANGELOG.md:', error.message);
            }

            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: '${{ steps.get_version.outputs.VERSION }}',
              name: '${{ steps.get_version.outputs.VERSION }}',
              body: releaseNotes,
              draft: false,
              prerelease: false
            });
